Blog.Web/Models/ArticleDetailViewModel.cs
using Blog.EntityLayer.Dtos;

namespace Blog.Web.Models
{
    public class ArticleDetailViewModel
    {
        public ArticleDto ArticleDto { get; set; } //Yorumlar ve Yazar Hakkinda icin gerekli
        public WriterArticlesViewModel WriterArticlesViewModel { get; set; } // Yazar Makaleleri icin gerekli
        public CategoryListDto CategoryListDto { get; set; } // Kategori Listesi icin gerekli
    }
}

Blog.Web/Models/CommentViewModel.cs
using System.Collections.Generic;
using Blog.EntityLayer.Concrete;
using Blog.EntityLayer.Dtos;

namespace Blog.Web.Models
{
    public class  CommentViewModel
    {
        public IList<Comment> Comments { get; set; }
        public Comment Comment { get; set; }
        public IList<Article> Articles { get; set; }
    }
}

Blog.Web/Models/ErrorViewModel.cs
using System;

namespace Blog.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Blog.Web/Models/UserComment.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Web.Models
{
    public class UserComment
    {
        public int Id { get; set; }
        public string UserName { get; set; }
    }
}

Blog.Web/Models/WriterArticlesViewModel.cs
using System.Collections.Generic;
using Blog.EntityLayer.Concrete;

namespace Blog.Web.Models
{
    public class WriterArticlesViewModel
    {
        public IList<Category> Categories { get; set; }
        public IList<Article> Articles { get; set; }
        public string Header { get; set; }
    }
}
 

Blog.Web/Controllers/ArticleController.cs
using Blog.BusinessLayer.Abstract;
using Blog.CoreLayer.Utilities.Results.ComplexTypes;
using Blog.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Blog.Web.Controllers
{
    public class ArticleController : Controller
    {
        private readonly IArticleService _articleService;
        private readonly ICategoryService _categoryService;

        public ArticleController(IArticleService articleService, ICategoryService categoryService)
        {
            _articleService = articleService;
            _categoryService = categoryService;
        }

        public async Task<IActionResult> Detail(int articleId,int writerId)
        {
            var articleResult = await _articleService.GetAsync(articleId);
            var articleResults = await _articleService.GetAllByViewCountAsync(isAscending: false, takeSize: 5); // Azalan bir sekilde yazarin 5 makalesi gelecek
            var categoriesResult = await _categoryService.GetAllByNonDeletedAndActiveAsync(); // Silmemis ve Aktif olan kategoriler

            if (articleResult.ResultStatus == ResultStatus.Success)
            {
                return View(new ArticleDetailViewModel
                {
                    ArticleDto = articleResult.Data,
                    WriterArticlesViewModel = new WriterArticlesViewModel
                    {
                        Articles = articleResults.Data.Articles,
                        Categories = categoriesResult.Data.Categories,
                        Header = ""
                    },
                    CategoryListDto = categoriesResult.Data
                });
            }
            return NotFound();
        }
    }
}

Blog.Web/Controllers/CommentController.cs
using Microsoft.AspNetCore.Mvc;

namespace Blog.Web.Controllers
{
    public class CommentController : Controller
    {
        [HttpPost]
        public PartialViewResult Add()
        {
            return PartialView("CommentAddPartial");
        }
    }
}

Blog.Web/Controllers/HomeController.cs
using System.Threading.Tasks;
using Blog.BusinessLayer.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IArticleService _articleService;

        public HomeController(IArticleService articleService)
        {
            _articleService = articleService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int? categoryId)
        {
            //var values = await _articleService.GetAllAsync();
            var articlesResult = await (categoryId == null
                ? _articleService.GetAllByNonDeletedAndActiveAsync()
                : _articleService.GetAllByCategoryAsync(categoryId.Value));
            return View(articlesResult.Data);
            //return View(values.Data);
        }
    }
}

Blog.Web/Controllers/RegisterController.cs
using System.Threading.Tasks;
using AutoMapper;
using Blog.BusinessLayer.Abstract;
using Blog.EntityLayer.Concrete;
using Blog.EntityLayer.Dtos;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Web.Controllers
{
    public class RegisterController : Controller
    {
        private readonly IWriterService _writerService;
        private readonly IMapper _mapper;

        public RegisterController(IWriterService writerService, IMapper mapper)
        {
            _writerService = writerService;
            _mapper = mapper;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(WriterAddDto writerAddDto)
        {
            var writer = _mapper.Map<Writer>(writerAddDto);
            var result = await _writerService.AddAsync(writerAddDto);

            return View();
        }
    }
}

Blog.Web/ViewComponents/Category/CategoryListViewComponent.cs
using System.Threading.Tasks;
using Blog.BusinessLayer.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Web.ViewComponents.Category
{
    public class CategoryListViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

Blog.Web/ViewComponents/Comment/CommentListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Blog.Web.ViewComponents.Comment
{
    public class CommentListViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

Blog.Web/ViewComponents/Writer/WriterAboutViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Blog.Web.ViewComponents.Writer
{
    public class WriterAboutViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

Blog.Web/ViewComponents/Writer/WriterArticlesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Blog.Web.ViewComponents.Writer
{
    public class WriterArticlesViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

Blog.Web/Views/Article/Detail.cshtml
@using System.Text.RegularExpressions
@model ArticleDetailViewModel
@{
    //ViewData["Title"] = "Detail";
    Layout = "_ArticleLayout";
    ViewBag.Title = Model.ArticleDto.Article.Title;
    ViewBag.Description = Model.ArticleDto.Article.SeoDescription;
    ViewBag.Author = Model.ArticleDto.Article.SeoAuthor;
    ViewBag.Tags = Model.ArticleDto.Article.SeoTags;
    Regex regex = new Regex("<[^>]*>"); //Editörden gelen text deki html etiketlerini kaldirmak icin kullaniyoruz.
}
<!--left-->
<div class="col-lg-8 left-blog-info-w3layouts-agileits text-left">
    <div class="blog-grid-top">
        <div class="b-grid-top">
            <div class="blog_info_left_grid">
                <a href="#">
                    <img src="~/CoreBlog/images/b1.jpg" class="img-fluid" alt="">
                </a>
            </div>
            <div class="blog-info-middle">
                <ul>
                    <li>
                        <a href="#"><i class="far fa-calendar-alt"></i> @Model.ArticleDto.Article.Date.ToShortDateString()</a>
                    </li>
                    <li class="mx-2">
                        <a href="#"><i class="fas fa-eye"></i> @Model.ArticleDto.Article.ViewCount</a>
                    </li>
                    <li>
                        <a href="#"><i class="far fa-comment"></i> @Model.ArticleDto.Article.CommentCount</a>
                    </li>
                </ul>
            </div>
        </div>
        <h1 class="mt-4">@Model.ArticleDto.Article.Title</h1>
        <!-- Author -->
        <p class="lead">@Model.ArticleDto.Article.Writer.FirstName @Model.ArticleDto.Article.Writer.LastName tarafından @Model.ArticleDto.Article.Date.ToShortDateString() tarihinde paylaşılmıştır.</p>
        <!-- Content -->
        @Html.Raw(Model.ArticleDto.Article.Content)
    </div>
    <br />
    <p class="text-center">Okunma Sayısı: <span class="badge badge-info">@Model.ArticleDto.Article.ViewCount</span> Yorum Sayısı: <span class="badge badge-warning">@Model.ArticleDto.Article.CommentCount</span></p>
    <hr>
    @await Html.PartialAsync("~/Views/Comment/CommentAddPartial.cshtml")
    @await Component.InvokeAsync("CommentList")
</div>
<div class="col-md-4">
    <!--right-->
    <div class="tech-btm">
        <img src="~/CoreBlog/images/banner1.jpg" class="card-img-top img-fluid" alt="">
    </div>
    <div class="tech-btm">
        <h4>Bültene Abone Ol</h4>
        <p>Mail adresinizi girerek yeniliklerden abone olabilirsiniz</p>
        <form action="#" method="post">
            <input type="email" placeholder="Email" required="">
            <input type="submit" value="Abone Ol">
        </form>
    </div>
    <!--Writer About-->
    @await Component.InvokeAsync("WriterAbout")
    <br />
    <!--// Writer About-->
    <!--Writer Blogs-->
    @await Component.InvokeAsync("WriterArticles")
    <!--// Writer Blogs-->
    <!--CategoryList-->
    <br />
    @await Component.InvokeAsync("CategoryList")
    <!--// CategoryList-->
    <br />
    <div class="single-gd tech-btm text-left">
        <h4>Son Eklenen Makale</h4>
        <div class="card" style="border-style: outset">
            <div class="blog-grids">
                <div class="blog-grid-left">
                    <a href="single.html">
                        <img src="~/CoreBlog/images/b1.jpg" class="card-img-top img-fluid" alt="">
                    </a>
                </div>
                <div class="blog-grid-right">
                    <h5>
                        <a href="single.html">Pellentesque dui, non felis. Maecenas male</a>
                    </h5>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
    </div>
    <div class="tech-btm widget_social text-left">
        <h4>Sosyal Medya</h4>
        <ul>
            <li>
                <a class="twitter" href="#">
                    <i class="fab fa-twitter"></i><span class="count">317K</span> Twitter Followers
                </a>
            </li>
            <li>
                <a class="facebook" href="#">
                    <i class="fab fa-facebook-f"></i><span class="count">218k</span> Twitter Followers
                </a>
            </li>
            <li>
                <a class="dribble" href="#">
                    <i class="fab fa-dribbble"></i><span class="count">215k</span> Dribble Followers
                </a>
            </li>
            <li>
                <a class="pin" href="#">
                    <i class="fab fa-pinterest"></i><span class="count">190k</span> Pinterest Followers
                </a>
            </li>
        </ul>
    </div>
    <div class="tech-btm">
        <h4>Son Makaleler</h4>
        <div class="blog-grids row mb-3 text-left">
            <div class="col-md-5 blog-grid-left">
                <a href="single.html">
                    <img src="~/CoreBlog/images/1.jpg" class="card-img-top img-fluid" alt="">
                </a>
            </div>
            <div class="col-md-7 blog-grid-right">

                <h5>
                    <a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
                </h5>
                <div class="sub-meta">
                    <span>
                        <i class="far fa-clock"></i> 20 Jan, 2018
                    </span>
                </div>
            </div>
        </div>
        <div class="blog-grids row mb-3 text-left">
            <div class="col-md-5 blog-grid-left">
                <a href="single.html">
                    <img src="~/CoreBlog/images/5.jpg" class="card-img-top img-fluid" alt="">
                </a>
            </div>
            <div class="col-md-7 blog-grid-right">

                <h5>
                    <a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
                </h5>
                <div class="sub-meta">
                    <span>
                        <i class="far fa-clock"></i> 20 Jan, 2018
                    </span>
                </div>
            </div>
            <div class="clearfix"> </div>
        </div>
        <div class="blog-grids row mb-3 text-left">
            <div class="col-md-5 blog-grid-left">
                <a href="single.html">
                    <img src="~/CoreBlog/images/3.jpg" class="card-img-top img-fluid" alt="">
                </a>
            </div>
            <div class="col-md-7 blog-grid-right">
                <h5>
                    <a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
                </h5>
                <div class="sub-meta">
                    <span>
                        <i class="far fa-clock"></i> 20 Feb, 2018
                    </span>
                </div>
            </div>
        </div>
    </div>
    <!--//right-->
</div>

Blog.Web/Views/Comment/CommentAddPartial.cshtml
<div class="comment-top">
    <h4>Bir yorum ekle</h4>
    <div class="comment-bottom">
        <form asp-controller="Comment" asp-action="Add" method="post" id="form-comment-add">
            <input class="form-control" type="text" name="Name" placeholder="İsim" required="">
            <input class="form-control" type="email" name="Email" placeholder="Email" required="">
            <input class="form-control" type="text" name="Subject" placeholder="Konu" required="">
            <textarea class="form-control" name="Message" placeholder="Mesaj..." required=""></textarea>
            <button type="submit" class="btn btn-primary submit">Ekle</button>
        </form>
    </div>
</div>

Blog.Web/Views/Home/Index.cshtml
@using System.Text.RegularExpressions
@model Blog.EntityLayer.Dtos.ArticleListDto
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
    Regex regex = new Regex("<[^>]*>"); //Editörden gelen text deki html etiketlerini kaldirmak icin kullaniyoruz.
}
<section class="main-content-w3layouts-agileits">
    <div class="container">
        <h3 class="tittle">Son Paylaşılan Makaleler</h3>
        <div class="inner-sec">
            <!--left-->
            <div class="left-blog-info-w3layouts-agileits text-left">
                <div class="row">
                    @foreach (var article in Model.Articles)
                    {
                        <div class="col-lg-4 card">
                            <a asp-controller="Article" asp-action="Detail" asp-route-articleId="@article.Id">
                                <img src="/CoreBlog/images/7.jpg" class="card-img-top img-fluid" alt="">
                            </a>
                            <div class="card-body">
                                <ul class="blog-icons my-4">
                                    <li>
                                        <a href="#"><i class="far fa-calendar-alt"></i> @article.Date.ToShortDateString()</a>
                                    </li>
                                    <li class="mx-2">
                                        <a href="#"><i class="far fa-comment"></i>@article.CommentCount</a>
                                    </li>
                                    <li>
                                        <a href="#"><i class="fas fa-eye"></i> @article.ViewCount</a>
                                    </li>
                                    <li>
                                        <i class="fab fa-kickstarter"></i> @article.Category.Name  @*Article.Category.Name ancak include parametre ile elde edilebilir*@
                                    </li>
                                </ul>
                                <h5 class="card-title">
                                    <a asp-controller="Article" asp-action="Detail" asp-route-articleId="@article.Id">@article.Title</a>
                                </h5>
                                <p class="card-text mb-3">
                                    @{
                                        article.Content = regex.Replace(article.Content, ""); //Html etiketlerini burada bos karakterle yer degistiriyoruz.
                                                                                              //Yukarida regex yerine su formatta kullanilabilirdi : @Hmtl.Raw(article.Content)
                                    }
                                    @(article.Content.Length > 150 ? article.Content.Substring(0, article.Content.Substring(0, 155).LastIndexOf(" ")) + "..." : article.Content + "...") @*sadece ilk 150 karakter, kücükse hata vermesini engelemek icin makalenin tamaminin gözükmesini sagliyoruz.*@
                                </p>
                                <a asp-controller="Article" asp-action="Detail" asp-route-articleId="@article.Id" class="btn btn-primary read-m">Daha fazla oku</a>
                            </div>
                        </div>
                    }
                </div>
                <!--//left-->
            </div>
        </div>
    </div>
</section>

Blog.Web/Views/Register/Index.cshtml
@using Blog.EntityLayer.Dtos
@model WriterAddDto
@{
    //ViewData["Title"] = "Index";
    Layout = "_UserLayout";
    ViewBag.Title = "Kayıt Ol";
    ViewBag.Description = "Yeni Yazar Kaydı";
    ViewBag.Tags = "Register, New Author, Yeni Kayıt, Kayıt Ol";
    ViewBag.Author = "Fatih's Blog";
}
<section class="main-content-w3layouts-agileits">
    <div class="container">
        <h3 class="tittle">Kayıt Ol</h3>
        <div class="inner-sec">
            <div class="login p-5 bg-light mx-auto mw-100">
                <form asp-action="Index" method="post" enctype="multipart/form-data">
                    @*<div class="form-row">*@
                        <div class="form-group">
                            <label class="small mb-1" for="layoutAuthentication">Yazar Kullanıcı Adı</label>
                            <input class="form-control py-4" @*id="inputEmailAddress"*@ type="text" placeholder="Kullanıcı Adınızı giriniz" asp-for="UserName" />
                            <span class="text-danger" asp-validation-for="UserName"></span>
                        </div>
                        <div class="form-group">
                            <label class="small mb-1" for="inputEmailAddress">E-Posta Adresi</label>
                            <input class="form-control py-4" id="inputEmailAddress" type="email" aria-describedby="emailHelp" placeholder="E-Posta Adresinizi giriniz" asp-for="Email" />
                            <span class="text-danger" asp-validation-for="Email"></span>
                        </div>
                        <div class="form-row">
                            <div class="col-md-6 mb-3">
                                <label for="validationCustom01">First name</label>
                                <input class="form-control py-4" id="inputFirstName" type="text" placeholder="Isminizi giriniz" asp-for="FirstName" />
                                @*<input type="text" class="form-control" id="validationDefault01" placeholder="" required="">*@
                                <span class="text-danger" asp-validation-for="FirstName"></span>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="validationCustom02">Last name</label>
                                <input class="form-control py-4" id="inputLastName" type="text" placeholder="Soyisminizi giriniz" asp-for="LastName" />
                                @*<input type="text" class="form-control" id="validationDefault02" placeholder="" required="">*@
                                <span class="text-danger" asp-validation-for="LastName"></span>
                            </div>
                        </div>
                    @*</div>*@
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="exampleInputPassword1 mb-2">Şifre</label>
                            @*<input type="password" class="form-control" id="password1" placeholder="" required="">*@
                            <input class="form-control py-4" id="inputPassword" type="password" placeholder="Şifrenizi giriniz" asp-for="Password" />
                            <span class="text-danger" asp-validation-for="Password"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="exampleInputPassword2 mb-2">Şifre Tekrarı</label>
                            @*<input type="password" class="form-control" id="password2" placeholder="" required="">*@
                            <input class="form-control py-4" id="inputConfirmPassword" type="password" placeholder="Şifrenizi tekrar giriniz" asp-for="Password" />
                            <span class="text-danger" asp-validation-for="Password"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="ImageFile"></label>
                            <input type="file" accept="image/*" class="form-control-file" asp-for="ImageFile" placeholder="Lütfen, resim seçiniz." />
                            <span class="text-danger" asp-validation-for="ImageFile"></span>
                        </div>
                    </div>
                    @*<button type="submit" class="btn btn-primary submit mb-4">Register</button>*@
                    <button type="button" class="btn btn-danger btn-block" data-dismiss="modal"><span class="fas fa-times"></span> İptal</button>
                    <button type="button" class="btn btn-primary btn-block" id="btnSave"><span class="fas fa-save"></span> Kaydet</button>
                    <br />
                    <p>
                        @* <a href="#">By clicking Signup, I agree to your terms</a>*@
                        <div class="small"><a href="login.html">Bir hesabın var mı? Giriş Yap</a></div>
                    </p>
                </form>
            </div>
        </div>
    </div>
</section>

Blog.Web/Views/Shared/Components/CategoryList/Default.cshtml
@model ArticleDetailViewModel

<div class="tech-btm">
    <h4>Kategoriler</h4>
    <ul class="list-group single">
        <a asp-controller="Home" asp-action="Index" class="nav-link collapsed" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <a asp-controller="Home" asp-action="Index">Tüm Kategoriler</a>
        </li>
        </a>
        @foreach (var category in Model.CategoryListDto.Categories)
        {
            <li class="list-group-item d-flex justify-content-between align-items-center">
                        <a asp-controller="Home" asp-action="Index" asp-route-categoryId="@category.Id">@category.Name</a>
                        <span class="badge badge-primary badge-pill">1</span>
            </li>
        }
    </ul>
</div>

Blog.Web/Views/Shared/Components/CommentList/Default.cshtml
@model ArticleDetailViewModel
<br />
<h4>Yorumlar</h4>
<div id="comments">
    @if (Model.ArticleDto.Article.Comments.Count == 0)
    {
        <div class="comment-top">
            <div class="media">
                <div class="media-body">
                    <h6>Bu bloğa ait bir yorum henüz yok. Bu bloğa ilk yorum yapan siz olun!</h6>
                </div>
            </div>
        </div>
    }
    else
    {
        @foreach (var comment in Model.ArticleDto.Article.Comments)
        {
            <div class="comment-top">
                <div class="media">
                    <img class="d-flex mr-3 rounded-circle" src="https://randomuser.me/api/portraits/men/34.jpg" alt="" /> @*"img-fluid"*@
                    <div class="media-body">
                        <h5 class="mt-0">
                            <i class="far fa-user"></i> @comment.CreatedByName
                        </h5>
                        <i class="far fa-clock"></i> @comment.CreatedDate.Date.ToShortDateString()
                        <br />
                        <br />
                        @comment.Content
                    </div>
                </div>
            </div>
        }
    }
</div>

Blog.Web/Views/Shared/Components/CommentListStatic/Default.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

Blog.Web/Views/Shared/Components/WriterArticles/Default.cshtml
@model ArticleDetailViewModel

<div class="card" style="border-style: outset">
    <h3 class="card-header text-center">Yazarın En Popüler Makaleleri</h3>
    <div class="tech-btm">
        <h4 class="card-header text-center">@Model.WriterArticlesViewModel.Header</h4>
        @for (int i = 0; i < Model.WriterArticlesViewModel.Articles.Count; i++)
        {
            if (i % 2 == 0)
            {
                <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-primary">
                    <a asp-controller="Article" asp-action="Detail" asp-route-categoryId="@Model.WriterArticlesViewModel.Articles[i].Id">@Model.WriterArticlesViewModel.Articles[i].Title - @Model.WriterArticlesViewModel.Articles[i].Date.ToShortDateString()</a>

                    @*<a href="/@Url.FriendlyUrlHelper(@Model.ArticleListDto.Articles[i].Title)/@Model.ArticleListDto.Articles[i].Id">@Model.ArticleListDto.Articles[i].Title - @Model.ArticleListDto.Articles[i].Date.ToShortDateString()</a>*@
                    @*<i class="far fa-clock"></i> @Model.WriterArticlesViewModel.Articles[i].Date.ToShortDateString()*@
                    <span class="badge-pill fas fa-eye"></span>@Model.WriterArticlesViewModel.Articles[i].ViewCount
                </li>
            }
            else
            {
                <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-danger">
                    <a asp-controller="Article" asp-action="Detail" asp-route-categoryId="@Model.WriterArticlesViewModel.Articles[i].Id">@Model.WriterArticlesViewModel.Articles[i].Title - @Model.WriterArticlesViewModel.Articles[i].Date.ToShortDateString()</a>
                    @*<a href="/@Url.FriendlyUrlHelper(@Model.ArticleListDto.Articles[i].Title)/@Model.ArticleListDto.Articles[i].Id">@Model.ArticleListDto.Articles[i].Title - @Model.ArticleListDto.Articles[i].Date.ToShortDateString()</a>*@
                    <span class="badge-pill fas fa-eye"></span>@Model.WriterArticlesViewModel.Articles[i].ViewCount
                </li>
            }
        }
    </div>
</div>

Blog.Web/Views/Shared/_UserLayoutCssPartial.cshtml
<link href="~/CoreBlog/css/bootstrap.css" rel='stylesheet' type='text/css' />
<link href="~/CoreBlog/css/single.css" rel="stylesheet" />
<link href="~/CoreBlog/css/jquery.desoslide.css" rel="stylesheet">
<link href="~/CoreBlog/css/style.css" rel='stylesheet' type='text/css' />
<link href="~/CoreBlog/css/fontawesome-all.css" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800" rel="stylesheet">
<link href="~/CoreBlog/css/site.css" rel="stylesheet" />

Blog.Web/Views/Shared/_UserLayoutHeaderLoginPartial.cshtml
<div class="col-md-4 top-forms text-center mt-lg-3 mt-md-1 mt-0">
    <span>Hoş Geldiniz</span>
    <span class="mx-lg-4 mx-md-2  mx-1">
        <a asp-controller="Home" asp-action="Login">
            <i class="fas fa-lock"></i> Giriş Yap
        </a>
    </span>
    <span>
        <a asp-controller="Register" asp-action="Index">
            <i class="far fa-user"></i> Üye Ol
        </a>
    </span>
</div>